[package]
name = "sccache"
version = "0.2.16-alpha.0"
authors = [
    "Ted Mielczarek <ted@mielczarek.org>",
    "Alex Crichton <alex@alexcrichton.com>",
]
license = "Apache-2.0"
description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
repository = "https://github.com/mozilla/sccache/"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = ["ccache"]
edition = "2018"

[badges]
travis-ci = { repository = "mozilla/sccache" }
appveyor = { repository = "mozilla/sccache" }

[[bin]]
name = "sccache"

[[bin]]
name = "sccache-dist"
required-features = ["dist-server"]

[dependencies]
anyhow = "1.0.38"
ar = { version = "0.8.0", optional = true }
atty = "0.2.14"
base64 = "0.13.0"
bincode = "1.3.1"
blake3 = "0.3.7"
byteorder = "1.4.2"
chrono = { version = "0.4.19", optional = true }
clap = "2.33.3"
counted-array = "0.1.2"
env_logger = "0.8.2"
filetime = "0.2.13"
flate2 = { version = "1.0.19", optional = true, default-features = false, features = ["rust_backend"] }
futures = { package = "futures", version = "0.3.12", features = ["compat", "thread-pool"] }
hmac = { version = "0.10.1", optional = true }
http = "0.2.3"
hyper = { version = "0.14.2", optional = true }
hyperx = { version = "1.3.0", optional = true }
jobserver = "0.1.21"
jsonwebtoken = { version = "7.2.0", optional = true }
lazy_static = "1.4.0"
libc = "0.2.82"
linked-hash-map = "0.5.4"
local-encoding = "0.2.0"
log = "0.4.13"
md-5 = { version = "0.9.1", optional = true }
memcached-rs = { version = "0.4.2", optional = true }
num_cpus = "1.13.0"
number_prefix = "0.4.0"
openssl = { version = "0.10.32", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
rand = "0.8.2"
redis = { version = "0.19.0", optional = true }
regex = "1.4.3"
reqwest = { version = "0.11.0", optional = true }
retry = "1.2.0"
ring = { version = "0.16.19", optional = true, features = ["std"] }
sha-1 = { version = "0.9.2", optional = true }
sha2 = { version = "0.9.2", optional = true }
serde = "1.0.119"
serde_derive = "1.0.119"
serde_json = "1.0.61"
strip-ansi-escapes = "0.1.0"
tar = "0.4.30"
tempfile = "3.2.0"
tokio-compat = "0.1.6"
tokio-io = "0.1.13"
tokio-process = "0.2.5"
tokio-serde-bincode = "0.2.1"
tower = "0.4.3"
tokio-tcp = "0.1.4"
tokio-timer = "0.2.13"
toml = "0.5.8"
untrusted = { version = "0.7.1", optional = true }
url = { version = "2.2.0", optional = true }
uuid = { version = "0.8.2", features = ["v4"] }
walkdir = "2.3.1"
# by default which pulls in an outdated failure version
which = { version = "4.0.2", default-features = false }
zip = { version = "0.5.9", default-features = false }
zstd = "0.6.0"

# dist-server only
crossbeam-utils = { version = "0.8.1", optional = true }
libmount = { version = "0.1.15", optional = true }
nix = { version = "0.19.1", optional = true }
rouille = { version = "3.0.0", optional = true, default-features = false, features = ["ssl"] }
syslog = { version = "5.0.0", optional = true }
void = { version = "1.0.2", optional = true }
version-compare = { version = "0.0.11", optional = true }
directories-next = "2.0.0"

[dev-dependencies]
assert_cmd = "1.0.2"
cc = "1.0.66"
chrono = "0.4.19"
itertools = "0.10.0"
predicates = "1.0.6"
selenium-rs = "0.1.2"

[target.'cfg(unix)'.dependencies]
daemonize = "0.4.1"
tokio-uds = "0.2.7"

[target.'cfg(windows)'.dependencies]
tokio-named-pipes = "0.1.0"
tokio-reactor = "0.1.12"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = ["fileapi", "handleapi", "winnls"]

[features]
default = ["all"]
all = ["dist-client", "redis", "s3", "memcached", "gcs", "azure"]
azure = ["chrono", "hyper", "hyperx", "url", "hmac", "md-5", "sha2"]
s3 = ["chrono", "hyper", "hyperx", "reqwest", "simple-s3", "hmac", "sha-1"]
simple-s3 = []
gcs = [
    "chrono",
    "hyper",
    "hyperx",
    "percent-encoding",
    "reqwest",
    "ring",
    "untrusted",
    "url",
]
memcached = ["memcached-rs"]
native-zlib = []
# Enable features that require unstable features of Nightly Rust.
unstable = []
# Enables distributed support in the sccache client
dist-client = ["ar", "flate2", "hyper", "hyperx", "reqwest", "url", "sha2"]
# Enables the sccache-dist binary
dist-server = [
    "crossbeam-utils",
    "jsonwebtoken",
    "flate2",
    "hyperx",
    "libmount",
    "nix",
    "openssl",
    "reqwest",
    "rouille",
    "syslog",
    "void",
    "version-compare",
]
# Enables dist tests with external requirements
dist-tests = ["dist-client", "dist-server"]

[workspace]
exclude = ["tests/test-crate"]
